Repository neo4j-examples/paradise-papers-django, pull requests merged in 2018-02, with the labels that each got.

#56 Add the navigation bar with the topics
  docs/conf.py
Labels: Ready for review

#50 Docs: Part 4
  docs/tutorial/part04.rst
Labels: Ready for review, all comments were addressed

#53 Docs: Part 5
  docs/tutorial/part05.rst
Labels: all comments were addressed

#54 Docs: Part 6
  docs/tutorial/part06.rst
Labels: all comments were addressed

#58 Update ReadMe
  README.md
Labels: Ready for review
